### ISSUE TITLE
The example that you shows on READ ME is not good.

### ISSUE THREAD

**Issue by kacunar** [gpvidal/adxl355-python#2]
Im still having problems with this code and the raspberry pi. First, the code dont run in python3 but yes in python2. Also, the ouput os the code dont match with the sensitivity of the sensor, if you see the example that you put on "read me" there are values like 787212 or 3152 and those values are out of the sensitivy range. I hope that you can help me.

**Comment by gpvidal** [comment]
Hi @kacunar ,

In which RPi are you running the code? What is the SO installed in RPi?
Probably it works in Python 2 (not tested), but I'm completely sure that it run in Python 3. 

The example in readme is that, an example. In fact, I took it in a previous version when the code had an error in axis conversion. For that reason, the numbers are out of range. :wink: 

Can you show me the error that appears to you?

**Comment by agustin1981** [comment]
Hello gpvidal , 

Thanks for your code it does read the raw values from the ADXL355.  I connected the device according to your recommendations and i am using a raspberry pi 3 with stretch. According to the library the device is running at a 2g Range so i tried to convert the raw values to G values using the 3.9 micro g  conversion scale on the data sheet. 
The raw values are exhibiting a similar behavior than the one described by kacunar above and are similar to the ones in your example, In other words the device is not giving me a 1 g or 0 g value at rest and it have a big fluctuation on the value range. 

Do i need to modify the raw values in a certain way before converting them to G values? , Is the fluctuation due to noise ? After the transformation the raw values will go from 0.9 to 3.90 G at rest. 

Thanks in advance for any  advice regarding this situation.

**Comment by gpvidal** [comment]
Hi @agustin1981 !
Yes, the code gives you the raw values in a different unit than G. And yes, the fluctuation is because the vibration (or noise).

To convert raw values to G unit, please check [this](https://ez.analog.com/thread/84039) example. :wink:
